name: Ryan Partridge - Portfolio
description: My portfolio website.

linkedin_url: 'https://www.linkedin.com/in/ryan-partridge-08b7118b/'
github_url: 'https://github.com/Achronus'

about_page_url: 'about'
portfolio_page_url: 'portfolio'
wiki_page_url: 'wiki'

collections:
  activities:
    output: true
  tags:
    output: true
  portfolio:
    output: true
    permalink: /:collection/:title
  wiki:
    output: true
    permalink: /:collection/:title
  wiki_categories:
    output: true
    collections_dir: /wiki/categories
    permalink: /:collection/:title
  wiki_topics:
    output: true
    collections_dir: /wiki/topics
    permalink: /:collection/:title
