name: Ryan Partridge - Portfolio
description: My portfolio website.

linkedin_url: 'https://www.linkedin.com/in/ryan-partridge-08b7118b/'
github_url: 'https://github.com/Achronus'
buymeacoffee_url: 'https://www.buymeacoffee.com/achronus'

about_page_url: 'about'
portfolio_page_url: 'portfolio'
blog_page_url: 'blog'

footer_text: 'All Rights Reserved. Created by me.'

collections:
  activities:
    output: true
  tags:
    output: true
  project_categories:
    output: true
  projects:
    output: true
    permalink: /:collection/:title
  blog_topics:
    output: true
    permalink: /blog/:title
  blog_articles:
    output: true

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
